version: "3.3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - type: bind
        source: .
        target: /workspace
    stdin_open: true
    tty: true
    working_dir: /workspace
